// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Parkmeter.Data.EF;

namespace Parkmeter.Data.Migrations
{
    [DbContext(typeof(ParkmeterContext))]
    [Migration("20170911062727_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Parkmeter.Core.Models.Parking", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Parkings");
                });

            modelBuilder.Entity("Parkmeter.Core.Models.Space", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ParkingID");

                    b.Property<int>("SpecialAttribute");

                    b.Property<int>("VehicleType");

                    b.HasKey("ID");

                    b.HasIndex("ParkingID");

                    b.ToTable("Spaces");
                });

            modelBuilder.Entity("Parkmeter.Core.Models.Space", b =>
                {
                    b.HasOne("Parkmeter.Core.Models.Parking", "Parking")
                        .WithMany("Spaces")
                        .HasForeignKey("ParkingID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
