// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Parkmeter.SDK.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Parking
    {
        /// <summary>
        /// Initializes a new instance of the Parking class.
        /// </summary>
        public Parking()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Parking class.
        /// </summary>
        public Parking(string name = default(string), IList<Space> spaces = default(IList<Space>), int? id = default(int?))
        {
            Name = name;
            Spaces = spaces;
            Id = id;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "spaces")]
        public IList<Space> Spaces { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

    }
}
