// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Parkmeter.SDK.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ParkingStatus
    {
        /// <summary>
        /// Initializes a new instance of the ParkingStatus class.
        /// </summary>
        public ParkingStatus()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ParkingStatus class.
        /// </summary>
        public ParkingStatus(int? parkingId = default(int?), int? totalAvailableSpaces = default(int?), int? busySpaces = default(int?), int? freeSpaces = default(int?), double? freePercentage = default(double?), double? busyPercentage = default(double?))
        {
            ParkingId = parkingId;
            TotalAvailableSpaces = totalAvailableSpaces;
            BusySpaces = busySpaces;
            FreeSpaces = freeSpaces;
            FreePercentage = freePercentage;
            BusyPercentage = busyPercentage;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "parkingId")]
        public int? ParkingId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "totalAvailableSpaces")]
        public int? TotalAvailableSpaces { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "busySpaces")]
        public int? BusySpaces { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "freeSpaces")]
        public int? FreeSpaces { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "freePercentage")]
        public double? FreePercentage { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "busyPercentage")]
        public double? BusyPercentage { get; private set; }

    }
}
