// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Parkmeter.SDK.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class PersistenceResult
    {
        /// <summary>
        /// Initializes a new instance of the PersistenceResult class.
        /// </summary>
        public PersistenceResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PersistenceResult class.
        /// </summary>
        public PersistenceResult(int? id = default(int?), int? state = default(int?), string message = default(string), IList<string> warnings = default(IList<string>))
        {
            Id = id;
            State = state;
            Message = message;
            Warnings = warnings;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "state")]
        public int? State { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "message")]
        public string Message { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "warnings")]
        public IList<string> Warnings { get; set; }

    }
}
