// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Parkmeter.SDK.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Space
    {
        /// <summary>
        /// Initializes a new instance of the Space class.
        /// </summary>
        public Space()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Space class.
        /// </summary>
        public Space(int? vehicleType = default(int?), int? specialAttribute = default(int?), int? parkingID = default(int?), int? id = default(int?))
        {
            VehicleType = vehicleType;
            SpecialAttribute = specialAttribute;
            ParkingID = parkingID;
            Id = id;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "vehicleType")]
        public int? VehicleType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "specialAttribute")]
        public int? SpecialAttribute { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "parkingID")]
        public int? ParkingID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

    }
}
